// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjKzMnKIeWojKoNmmRgn2gqy-GCxXON48',
    appId: '1:1014176021512:android:70b2f63bce5f0cc7aa25bd',
    messagingSenderId: '1014176021512',
    projectId: 'flutterfirebasetutorial-ab4c9',
    storageBucket: 'flutterfirebasetutorial-ab4c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7cFpcvN8n3pTLmo6yWI7Y4585r0m_njI',
    appId: '1:1014176021512:ios:394c90693b95be10aa25bd',
    messagingSenderId: '1014176021512',
    projectId: 'flutterfirebasetutorial-ab4c9',
    storageBucket: 'flutterfirebasetutorial-ab4c9.appspot.com',
    androidClientId: '1014176021512-8kt9k1vldpid3lj26jm8qp242uvjo2cm.apps.googleusercontent.com',
    iosClientId: '1014176021512-ivoikm0r9kjpfd65s3c6kb41e8tr989b.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.flutter.app',
  );
}
